var fruit = ["banana", "apple", "orange", "watermelon"];
var vegetables = ["carrot", "tomato", "pepper", "lettuce"];
vegetables.pop()
// console.log(vegetables)
fruit.shift()
// console.log(fruit)
fruit.indexOf("orange")
// console.log(fruit)
fruit.push("1")
// console.log(fruit)
var length = vegetables.length
// console.log(length)
vegetables.push(length)
// console.log(vegetables)
var food = fruit.concat(vegetables)
// console.log(food)
food.splice(4, 2)
// console.log(food)
food.reverse()
// console.log(food)
var reversed = food.join(",")
// console.log(reversed)